title: "The Blaze Times | Web Stories"
twitter_username: "theblazetimes_x"
email: theblazetimes@gmail.com
description: "A collection of Google Web Stories"
url: "https://theblazetimes-git.github.io" # Change with your GitHub Pages URL
baseurl: "web-stories" # Adjust this based on your setup
theme: jekyll-theme-minimal # Optional theme

collections:
  stories:
    output: true
    permalink: /:name.html  # Web story will be available at /today-is-happy.html

plugins:
  - jekyll-sitemap  # Add this line to enable the sitemap plugin
